name: Submit Collection Block Metadata to Registry

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  submit-pr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        collection-name:
          - "prefect-airbyte"
          - "prefect-aws"
          - "prefect-azure"
          - "prefect-bitbucket"
          - "prefect-census"
          - "prefect-databricks"
          - "prefect-dbt"
          - "prefect-docker"
          - "prefect-email"
          - "prefect-firebolt"
          - "prefect-gcp"
          - "prefect-github"
          - "prefect-gitlab"
          - "prefect-great-expectations"
          - "prefect-hex"
          - "prefect-hightouch"
          - "prefect-jupyter"
          - "prefect-kubernetes"
          - "prefect-monday"
          - "prefect-monte-carlo"
          - "prefect-openai"
          - "prefect-openmetadata"
          - "prefect-shell"
          - "prefect-slack"
          - "prefect-snowflake"
          - "prefect-sqlalchemy"
          - "prefect-twitter"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ${{ matrix.collection-name }}
        run: |
          python -m pip install --upgrade pip build
          python -m pip install --upgrade --upgrade-strategy eager "${{ matrix.collection-name }}[all_extras]"

      - name: Generate collection block metadata
        run: |
          python src/generate_block_metadata.py ${{ matrix.collection-name }}

      - name: Submit PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Updating ${{ matrix.collection-name }} metadata
          branch: update-${{ matrix.collection-name }}-metadata
          delete-branch: true
          title: Update ${{ matrix.collection-name }} metadata with new releases
          body: |
            Automated PR created to update ${{ matrix.collection-name }} metadata.
            Feel free to make any necessary changes to this PR before merging.
          labels: |
            update metadata
            automated pr
