name: Submit Collection Metadata to Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  submit-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Merge collection metadata
        run: |
          python merge_collection_metadata.py

      - name: Submit PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Merging collections metadata
          branch: merge-collections-metadata
          delete-branch: true
          title: Update collections metadata with new releases
          body: |
            Automated PR created to merge collections metadata.
            Feel free to make any necessary changes to this PR before merging.
          labels: |
            merge metadata
            automated pr
